name: 'Spage Release Action'
description: 'Publish your website to Spage'
author: 'Spage Team'
runs:
  using: 'node20'
  main: 'dist/main.js'
inputs:
  url:
    description: 'Control panel URL'
    required: true
  dist:
    description: 'Site dist directory, e.g., ./dist'
    required: true
  site-id:
    description: 'Site ID'
    required: true
  tag:
    description: 'Tag for the release, e.g., v1.0.0, default is latest'
    required: false
    default: 'latest'
  is-temp:
    description: 'Is this a temporary release? If true, the site will not be published to the public'
    required: false
    default: 'false'
outputs:
  site-url:
    description: 'The URL of the site after the release'