name: build dist

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install and build
        run: |
          npm install -g pnpm
          pnpm install
          pnpm build

      - name: Push Change
        run: |
          # typescript compile
          git config --local user.name "liteyuki-flow"
          git config --local user.email "liteyuki-flow@liteyuki.org"
          git add dist/
          git commit -m "📦 update dist"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
